databases:
  - name: shopzone-db
    plan: free
    databaseName: storezone
    user: shopzone_user

services:
  - type: web
    name: store-checkout-stripe
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_NAME
        value: StoreCheckout
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://store-checkout-stripe.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: shopzone-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: shopzone-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: shopzone-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: shopzone-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: shopzone-db
          property: password
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
